### ISSUE TITLE
Disconnect method doesn't work. Throws unhandled exception. 

### ISSUE THREAD

**Issue by MadsEibye** [brim-borium/spotify_sdk#83] opened 2021-03-24 16:45 UTC
**Describe the bug**
The applicaton crashed when trying to disconnect the app from spotifysdk. It throws an unhandled exeption with error message "The method '+' was called on null.". Seems like some sort of issue with the sdk, since I have just used the disconnect method. Everything else in the sdk works just fine for me.

**To Reproduce**
I believe the error is not in my code, meaning it should crash everytime someone calls the disconnect method. If that is not so, the mistake occours when I press a button calling the SpotifySdk.disconnect() method. Codesnippet is below.

**Expected behavior**
I expected the method to log me out of the app and request a new login on new launch.

**Screenshots**
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '+' was called on null.
E/flutter ( 3774): Receiver: null
E/flutter ( 3774): Tried calling: +("")
E/flutter ( 3774): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 3774): #1      SpotifySdk._logException
package:spotify_sdk/spotify_sdk.dart:548
E/flutter ( 3774): #2      SpotifySdk.disconnect
package:spotify_sdk/spotify_sdk.dart:125
E/flutter ( 3774): <asynchronous suspension>
E/flutter ( 3774): #3      UserProfilePage.build.<anonymous closure>
package:flutter_app/userProfilePage.dart:129
E/flutter ( 3774): #4      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter ( 3774): #5      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter ( 3774): #6      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter ( 3774): #7      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter ( 3774): #8      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter ( 3774): #9      BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter ( 3774): #10     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter ( 3774): #11     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter ( 3774): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter ( 3774): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 3774): #14     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter ( 3774): #15     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter ( 3774): #16     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358
E/flutter ( 3774): #17     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter ( 3774): #18     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter ( 3774): #19     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter ( 3774): #20     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter ( 3774): #21     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter ( 3774): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 3774): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 3774): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 3774): #25     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 3774): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 3774):

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser []
 - Version [Windows 10?]

**Smartphone (please complete the following information):**
 - Device: [Android Emulator ]
 - OS: [Android Api LVL 28]

**Additional context**
Future<void> disconnect() async {
    try {
      var result = await SpotifySdk.disconnect();
      setStatus(result ? 'disconnect successful' : 'disconnect failed');
    } on PlatformException catch (e) {
      setStatus(e.code, message: e.message);
    } on MissingPluginException {
      setStatus('not implemented');
    }
  }

**Comment by brim-borium** [comment] 2021-03-27 12:23
Hi @MadsEibye I tested the behavior with the example app included in the package and was not able to reproduce this.

> I expected the method to log me out of the app and request a new login on new launch.

You have to call the connectToSpotifySdk yourself again after you requested the disconnect. But also this seems to work on the example.


Could you add the code that calls the disconnect method you provided here?

**Comment by itsMatoosh** [comment] 2021-04-06 22:53
This is possibly fixed by #89

**Comment by brim-borium** [comment] 2021-04-19 06:39
@MadsEibye we released a new version, do you still have this issue ?

**Comment by fotiDim** [comment] 2021-05-07 07:48
Closing this as stale. Feel free to comment if you are still facing the issue.

**Closed by fotiDim** 2021-05-07 07:48 UTC
Labels: android, awaiting-clarification
