### ISSUE TITLE
Get authorization code only

### ISSUE THREAD

**Issue by wackazong** [brim-borium/spotify_sdk#153] opened 2022-01-18 17:52 UTC
**Is your feature request related to a problem? Please describe.**
I want  to have a refresh token on iOS and Android in order to be able to to refresh the access token.

**Describe the solution you'd like**
Is it possible to obtain the authorization code from the SDK on iOS and Android? Then I could use that to swap it for an access token and refresh token on my own server.

**Describe alternatives you've considered**
I see that there is the token swap case, but this is not implemented for iOS and not available for Android

**Comment by vikrantyadav7** [comment] 2022-01-24 15:10
yes it would improve the user experience overall .
please make it happen soon.

**Comment by fotiDim** [comment] 2022-01-24 18:17
Closing as duplicate of https://github.com/brim-borium/spotify_sdk/issues/113

**Closed by fotiDim** 2022-01-24 18:17 UTC
Labels: enhancement
