### ISSUE TITLE
about scope problem

### ISSUE THREAD

**Issue by mattun** [brim-borium/spotify_sdk#73] opened 2021-02-12 18:56 UTC
```
var authenticationToken = await SpotifySdk.getAuthenticationToken(
          clientId: DotEnv.env['CLIENT_ID'].toString(),
          redirectUrl: DotEnv.env['REDIRECT_URL'].toString(),
          scope: 'app-remote-control, '
              'user-modify-playback-state, '
              'playlist-read-private, '
              'user-read-playback-state, '
              'playlist-modify-public, '
              'user-read-currently-playing,user-read-recently-played');
```

I wanna edit the playlist, so I added playlist-modify-public.
But when moved to Spotify , didn't appear the correct message for playlist-modify-public.

<img src="https://user-images.githubusercontent.com/113253/107809934-39b80e00-6daf-11eb-9f98-6f49da06a511.PNG" width="320">

**Comment by ndahlquist** [comment] 2021-02-12 21:22
I think this may be a duplicate of https://github.com/brim-borium/spotify_sdk/issues/69, which was resolved but is pending a release. @fotiDim , would it be possible to get a release of this?

**Comment by mattun** [comment] 2021-02-13 05:27
wow great!!! Thanks!! I am looking forward to release too.

**Comment by brim-borium** [comment] 2021-02-13 06:53
Hi I will make a new release today or tomorrow :)

**Comment by brim-borium** [comment] 2021-02-14 17:45
Update on this: 
I made a new PR that I want to merge before releasing the new version: #74
That brings all packages up to date and also fixes some issues we have on pub.dev

**Comment by brim-borium** [comment] 2021-02-15 09:03
New version has been released 
https://pub.dev/packages/spotify_sdk

Closing this issue now. If you encounter any issues please open a new issue :)

**Closed by brim-borium** 2021-02-15 09:03 UTC
