### ISSUE TITLE
Invalid Authorization Code Error

### ISSUE THREAD

**Issue by TarunGunampalli** [brim-borium/spotify_sdk#96] opened 2021-04-13 21:58 UTC
**Describe the bug**
I use the given getAuthenticationToken function which returns an Authentication Token and seems to work correctly. However, when I proceed to use the returned token to try to get an access token by passing it in the body to a call to https://accounts.spotify.com/api/token, I receive this error: `{error: invalid_grant, error_description: Invalid authorization code}`
Right now to test, I'm using the example app.

**To Reproduce**
1. Call getAuthenticationToken with the correct parameters (client id and redirect uri)
2. Make a post request to 'https://accounts.spotify.com/api/token' with the returned authentication token with the other required parameters (client id, client secret, grant type, and redirect uri)

**Expected behavior**
It should return an access token and refresh token that I can use to access the spotify web api.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, running application on Android emulator

**Comment by wackazong** [comment] 2022-01-18 17:11
I would say what you get back from `getAuthenticationnToken` is already the access token.

**Comment by fotiDim** [comment] 2022-01-19 15:22
I believe the Authentication Token is the access token. No additional steps needed.

**Comment by wackazong** [comment] 2022-01-19 15:34
Yes, that is what I think, too.

**Comment by vikrantyadav7** [comment] 2022-01-24 15:08
yes , but it will be a better experience for a user .because now if my access token expires i have to again call getAuthToken and that displays a loading sign , its okay for a few time but every hour it seems annoying . And if i have refresh token and access token then i can get new access token through my backend improving the user experience.

**Comment by fotiDim** [comment] 2022-01-24 18:16
Closing as duplicate of https://github.com/brim-borium/spotify_sdk/issues/113

**Closed by fotiDim** 2022-01-24 18:16 UTC
Labels: android
