### ISSUE TITLE
Not properly Initializing Spotify js dependencies

### ISSUE THREAD

**Issue by NoahIles** [brim-borium/spotify_sdk#100] opened 2021-05-14 11:40 UTC
**Describe the bug**
Every time I restart my Flutter App I need to hot reload after attempting connection to the API.  Bug occurs on both Android emulator and flutter for web. 

**To Reproduce**
Fully Stop and restart the app

**Expected behavior**
I expect to not need to hot reload in order to utilize your package/

**Screenshots**
This is the only exception I get.
![image](https://user-images.githubusercontent.com/31051719/118265121-963dce80-b46d-11eb-90a1-be583914fe86.png)
After restarting this is what outputs: 
![image](https://user-images.githubusercontent.com/31051719/118265736-73f88080-b46e-11eb-808c-671aa245f62e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: Android 

After digging a little deeper I think my error is 
starting when I call SpotifySdk.getAuthenticationToken()
`<getObject: NoSuchMethodError: The getter 'uri' was called on null.>`

**Comment by max-novak** [comment] 2021-06-02 17:42
![image](https://user-images.githubusercontent.com/42859327/120526341-ac570300-c40b-11eb-8c6f-b1bcf65d9523.png)

I have only ran flutter with web using this package

Both spotify_sdk: ^2.0.0 and spotify_sdk: ^2.1.0 output the same error when I run
`var result = await SpotifySdk.connectToSpotifyRemote(clientId: dotenv.env['CLIENT_ID'].toString(), redirectUrl: dotenv.env['REDIRECT_URL'].toString());`

I am certain my `dotenv.env['CLIENT_ID']` and `dotenv.env['REDIRECT_URL']` are both correct. I reckon Spotify altered how they publish their sdk recently.

**Comment by nzoschke** [comment] 2021-06-12 19:58
This might be a dupe of https://github.com/brim-borium/spotify_sdk/issues/80

The error goes away if you run your app with `flutter run -d chrome --release` (vs default debug mode)

**Comment by fotiDim** [comment] 2021-06-29 08:17
@NoahIles did you address the issue?

**Comment by incvv** [comment] 2021-09-18 21:13
I found a workaround - download Spotify SDK in `index.html`:
```
  <script src="https://sdk.scdn.co/spotify-player.js"></script>
  <script>
    window.onSpotifyWebPlaybackSDKReady = (evt) => {

    };
  </script>
```

The `window.onSpotifyWebPlaybackSDKReady` is necessary because spotify_sdk_web detects it, assumes that the SDK has been initialized, and skips adding the `<script src="https://sdk.scdn.co/spotify-player.js"></script>` to the DOM (which is when the JS error occurs).

Just be sure to not call spotify_sdk_web methods before the Spotify SDK is actually initialized (by waiting, or more cleanly by interacting with the JS in your own code to find out when it's initialized).

**Comment by fotiDim** [comment] 2021-10-01 21:18
@incvv do you think you can make a PR about it and also update the readme accordingly?

**Comment by fotiDim** [comment] 2021-11-27 16:32
Closed via https://github.com/brim-borium/spotify_sdk/pull/145

**Closed by fotiDim** 2021-11-27 16:32 UTC
Labels: web
